name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: 1.11.1.1113
      - run: ./cypress/cypress.sh
        shell: bash
